### PR TITLE
Created FS.Utility.eachFileFromPath, a server-side helper method

### PR DESCRIPTION
**Pull request by rhyslbw**
Just putting this forward for review and consideration to be included in the FS.Utility space.

- Based on FS.Utility.eachFile
- String passed to fs.readdir, with the results mapped to and array with the full path of each file in the directory, filtered using isFile()
- Each file then passed as the first param to the supplied function
- If an error is thrown as part of the readdir, a Meteor.Error is thrown.

As a side-note I'm working on a generic server directory browser package that I might use as the foundation for a CFS integrated version. It will be a handy tool for anyone needing to provide functionality to an admin user to import from a server path into an FS.Collection.

### CODE REVIEW

**Comment by raix** [comment]
@rhyslbw Its a good idea, I'll wait on merging to hear what @aldeed thinks,

Btw. I'm thinking if we ought to have a folder api on the storage adapters them selfs at some point? eg.: `files.each('/folder', function(file) { /* file.isFile / file.isDirectory file.name etc. */ }); - I think most of the SA's support this.

**Comment by aldeed** [comment]
I like it. Folder API on the SAs makes some sense, too. Not sure about gridfs.

**Comment by rhyslbw** [comment]
Great. +1 for folder API. Might allow for a more powerful way to define a custom filekey for the store in situations where directories need to be created etc

**Comment by rhyslbw** [comment]
Migrated to main repo: https://github.com/CollectionFS/Meteor-CollectionFS/pull/617

**Comment by rhyslbw** [comment]
Folder API enhancement tracked here: https://github.com/CollectionFS/Meteor-CollectionFS/issues/618

**Pull request closed without merging**
